services:
  # ──────────── PostgreSQL Database ────────────
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servicedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # ──────────── NATS JetStream 3-node cluster ────────────
  nats-1:
    image: nats:2.10-alpine
    command: >
      -js
      -server_name nats-1
      -store_dir /data/jetstream
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-2:6222,nats://nats-3:6222
    volumes:
      - n1-data:/data/jetstream
    ports:
      - "4222:4222" # client
      - "8222:8222" # monitoring

  nats-2:
    image: nats:2.10-alpine
    command: >
      -js
      -server_name nats-2
      -store_dir /data/jetstream
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-3:6222
    volumes:
      - n2-data:/data/jetstream

  nats-3:
    image: nats:2.10-alpine
    command: >
      -js
      -server_name nats-3
      -store_dir /data/jetstream
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-2:6222
    volumes:
      - n3-data:/data/jetstream

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mqtt.address=:1883"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=alirahbar2005@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt

  # ──────────── Device-onboarding API ────────────
  service-io:
    build: .
    depends_on:
      - nats-1
      - nats-2
      - nats-3
      - postgres
      - traefik

    restart: on-failure
    environment:
      NATS_URL: nats://nats-1:4222
      DATABASE_DSN: "postgres://user:password@postgres:5432/servicedb?sslmode=disable"
      LISTEN_ADDR: ":9090"
      ADAPTER_MAP_JSON: '{"random":"registry.digitalocean.com/scadable-container-registry/adapter-rand:latest", "mqtt":"registry.digitalocean.com/scadable-container-registry/adapter-mqtt:latest"}'
      DO_REGISTRY_TOKEN: "dop_v1_0c287cb3b1706411b5026b7eb1c82e64ae02449f32243ad19971283f17407387"
      TRAEFIK_NETWORK: "service-io_default"
      TRAEFIK_ENTRYPOINT: "websecure"
      TRAEFIK_CERT_RESOLVER: "myresolver"
      BASE_DOMAIN: "localhost"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"

volumes:
  postgres-data:
  n1-data:
  n2-data:
  n3-data: