services:
  # ──────────── PostgreSQL Database ────────────
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servicedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # ──────────── NATS JetStream 3-node cluster ────────────
  nats-1:
    image: nats:2.10-alpine
    command: >
      -js
      -server_name nats-1
      -store_dir /data/jetstream
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-2:6222,nats://nats-3:6222
    volumes:
      - n1-data:/data/jetstream
    ports:
      - "4222:4222" # client
      - "8222:8222" # monitoring

  nats-2:
    image: nats:2.10-alpine
    command: >
      -js
      -server_name nats-2
      -store_dir /data/jetstream
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-3:6222
    volumes:
      - n2-data:/data/jetstream

  nats-3:
    image: nats:2.10-alpine
    command: >
      -js
      -server_name nats-3
      -store_dir /data/jetstream
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-2:6222
    volumes:
      - n3-data:/data/jetstream

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.mqtts.address=:8883"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=digitalocean"
      - "--certificatesresolvers.myresolver.acme.email=alirahbar2005@gmail.com" # Change this email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.filename=/etc/traefik/dynamic/traefik_mqtt.yml"
      - "--providers.file.watch=true"

    environment:
      - DO_AUTH_TOKEN=dop_v1_d97af8b5d18661923aceb56921507fb83db08cfefd4e289d59ec61bd30dce1b4
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8085:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Users/ali/GolandProjects/service-io/docker-compose.yaml:/etc/traefik/dynamic/traefik_mqtt.yaml:ro
      - /root/letsencrypt:/letsencrypt

    restart: unless-stopped


  # ──────────── Device-onboarding API ────────────
  # In service-io/docker-compose.yaml

    # ... (postgres, nats, traefik services) ...

    # ──────────── Device-onboarding API ────────────
  service-io:
      build: .
      depends_on:
        - nats-1
        - nats-2
        - nats-3
        - postgres
        - traefik

      restart: on-failure
      environment:
        NATS_URL: nats://nats-1:4222
        DATABASE_DSN: "postgres://user:password@postgres:5432/servicedb?sslmode=disable"
        LISTEN_ADDR: ":9090"
        ADAPTER_MAP_JSON: '{"random":"registry.digitalocean.com/scadable-container-registry/adapter-rand:latest", "mqtt":"registry.digitalocean.com/scadable-container-registry/adapter-mqtt:latest"}'
        DO_REGISTRY_TOKEN: "dop_v1_0c287cb3b1706411b5026b7eb1c82e64ae02449f32243ad19971283f17407387"
        TRAEFIK_NETWORK: "service-io_default"
        # ✅ FIX: TRAEFIK_ENTRYPOINT is not needed for TCP routers. You can remove this line.
        # TRAEFIK_ENTRYPOINT: "websecure"
        TRAEFIK_CERT_RESOLVER: "myresolver"
        # ✅ FIX: Change this to your actual domain to enable MQTTS.
        # When this is "localhost", it will generate insecure labels.
        BASE_DOMAIN: "io.scadable.com" # Or whatever your domain is
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "9090:9090"

volumes:
  postgres-data:
  n1-data:
  n2-data:
  n3-data: