services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=servicedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nats-1:
    image: nats:2.10-alpine
    command: |
      -js
      -server_name nats-1
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-2:6222,nats://nats-3:6222
    ports:
      - "4222:4222"
      - "8222:8222" # monitoring

  nats-2:
    image: nats:2.10-alpine
    command: |
      -js
      -server_name nats-2
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-3:6222

  nats-3:
    image: nats:2.10-alpine
    command: |
      -js
      -server_name nats-3
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats-1:6222,nats://nats-2:6222

volumes:
  postgres-data: